---
services:
  02dpage-pgadmin4:
    init: ${DOCKER_INIT}
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_SHELL_HISTORY: ${GLOBAL_STACK_SHELL_HISTORY}
        GLOBAL_STACK_IMAGE_DPAGE_PGADMIN4_VERSION: ${GLOBAL_STACK_IMAGE_DPAGE_PGADMIN4_VERSION}
      context: ./
      dockerfile: ./docker/images/02dpage-pgadmin4/Dockerfile
    depends_on:
      - 00base
    environment:
      - PGADMIN_DEFAULT_EMAIL=${GLOBAL_STACK_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${GLOBAL_STACK_PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS=['local.io']
    networks:
      - public
    ports:
      - ${GLOBAL_STACK_DPAGE_PGADMIN4_PORT_80:-}80
      - ${GLOBAL_STACK_DPAGE_PGADMIN4_PORT_443:-}443
    restart: unless-stopped
    volumes:
      - ./docker/data/dumps/dpage-pgadmin4:/var/lib/pgadmin/storage/tames_local.io:rw
      - pgadmin_lib:/var/lib/pgadmin:rw,delegated
volumes:
  pgadmin_lib:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_pgadmin_lib
