---
services:
  03nodeedge:
    init: ${DOCKER_INIT}
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/03nodeedge/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      00base:
        condition: service_healthy
        required: true
      02nvm:
        condition: service_healthy
        required: true
    extra_hosts:
      - ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    environment:
      - NVM_MODE=setup
      - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
      - GLOBAL_STACK_DENO_ALEPH_VERSION=${GLOBAL_STACK_DENO_ALEPH_VERSION}
      - GLOBAL_STACK_DENO_MANDARINETS_VERSION=${GLOBAL_STACK_DENO_MANDARINETS_VERSION}
      - GLOBAL_STACK_DENO_VERSION=${GLOBAL_STACK_DENO_VERSION}
      - GLOBAL_STACK_NVM_VERSION=${GLOBAL_STACK_NVM_VERSION}
      - GLOBAL_STACK_RELOAD_NVM=${GLOBAL_STACK_RELOAD_NVM}
      - DENO_INSTALL=${GLOBAL_STACK_DENO_INSTALL}
      - DENO_INSTALL_ROOT=${GLOBAL_STACK_DENO_INSTALL_ROOT}
      - DENO_DIR=${GLOBAL_STACK_DENO_DIR}
      - BUN_INSTALL=${GLOBAL_STACK_BUN_INSTALL}
      - NVM_DIR=${GLOBAL_STACK_NVM_DIR}
      - YARN_OFFLINE_MIRROR=${GLOBAL_STACK_YARN_OFFLINE_MIRROR}
      - YARN_CACHE_FOLDER=${GLOBAL_STACK_YARN_CACHE_FOLDER}
      - YARN_GLOBAL_FOLDER=${GLOBAL_STACK_YARN_GLOBAL_FOLDER}
      - GLOBAL_STACK_PNPM_GLOBAL_DIR=${GLOBAL_STACK_PNPM_GLOBAL_DIR}
      - PNPM_HOME=${GLOBAL_STACK_PNPM_GLOBAL_DIR}
      - GLOBAL_STACK_PNPM_STORE_DIR=${GLOBAL_STACK_PNPM_STORE_DIR}
      - NPM_CACHE_DIR=${GLOBAL_STACK_NPM_CACHE_DIR}
      - CYPRESS_CACHE_FOLDER=${GLOBAL_STACK_CYPRESS_CACHE_FOLDER}
      - NODE_VERSION_AS=${GLOBAL_STACK_NODEEDGE_VERSION_AS}
      - NODE_VERSION=${GLOBAL_STACK_NODEEDGE_VERSION}
      - GLOBAL_STACK_NODE_UPGRADE=${GLOBAL_STACK_NODEEDGE_UPGRADE}
      - GLOBAL_STACK_NODE_UPGRADE_ALL=${GLOBAL_STACK_NODEEDGE_UPGRADE_ALL}
      - NODE_CONFIG_PACKAGE_DUMMY_NAME=dummy
      - NODE_INSTALL_PACKAGE_DUMMY_VERSION=0
      - NODE_CONFIG_PACKAGE_ANGULAR_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_ANGULAR_CLI_NAME}
      - NODE_INSTALL_PACKAGE_ANGULAR_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_ANGULAR_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_ANGULAR_DEVKIT_ARCHITECT_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_ANGULAR_DEVKIT_ARCHITECT_CLI_NAME}
      - NODE_INSTALL_PACKAGE_ANGULAR_DEVKIT_ARCHITECT_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_ANGULAR_DEVKIT_ARCHITECT_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_ANGULAR_DEVKIT_SCHEMATICS_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_ANGULAR_DEVKIT_SCHEMATICS_CLI_NAME}
      - NODE_INSTALL_PACKAGE_ANGULAR_DEVKIT_SCHEMATICS_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_ANGULAR_DEVKIT_SCHEMATICS_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_CAPACITOR_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_CAPACITOR_CLI_NAME}
      - NODE_INSTALL_PACKAGE_CAPACITOR_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_CAPACITOR_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_COLORS_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_COLORS_NAME}
      - NODE_INSTALL_PACKAGE_COLORS_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_COLORS_VERSION}
      - NODE_CONFIG_PACKAGE_COMMITIZEN_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_COMMITIZEN_NAME}
      - NODE_INSTALL_PACKAGE_COMMITIZEN_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_COMMITIZEN_VERSION}
      - NODE_CONFIG_PACKAGE_COMMITLINT_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_COMMITLINT_CLI_NAME}
      - NODE_INSTALL_PACKAGE_COMMITLINT_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_COMMITLINT_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_COMMITLINT_CONFIG_CONVENTIONAL_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_COMMITLINT_CONFIG_CONVENTIONAL_NAME}
      - NODE_INSTALL_PACKAGE_COMMITLINT_CONFIG_CONVENTIONAL_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_COMMITLINT_NAME_CONVENTIONAL_VERSION}
      - NODE_CONFIG_PACKAGE_CONCURRENTLY_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_CONCURRENTLY_NAME}
      - NODE_INSTALL_PACKAGE_CONCURRENTLY_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_CONCURRENTLY_VERSION}
      - NODE_CONFIG_PACKAGE_CORDOVA_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_CORDOVA_NAME}
      - NODE_INSTALL_PACKAGE_CORDOVA_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_CORDOVA_VERSION}
      - NODE_CONFIG_PACKAGE_CORDOVA_RES_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_CORDOVA_RES_NAME}
      - NODE_INSTALL_PACKAGE_CORDOVA_RES_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_CORDOVA_RES_VERSION}
      - NODE_CONFIG_PACKAGE_DEGIT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_DEGIT_NAME}
      - NODE_INSTALL_PACKAGE_DEGIT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_DEGIT_VERSION}
      - NODE_CONFIG_PACKAGE_EMBER_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_EMBER_CLI_NAME}
      - NODE_INSTALL_PACKAGE_EMBER_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_EMBER_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_ESLINT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_ESLINT_NAME}
      - NODE_INSTALL_PACKAGE_ESLINT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_ESLINT_VERSION}
      - NODE_CONFIG_PACKAGE_EXPRESS_GENERATOR_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_EXPRESS_GENERATOR_NAME}
      - NODE_INSTALL_PACKAGE_EXPRESS_GENERATOR_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_EXPRESS_GENERATOR_VERSION}
      - NODE_CONFIG_PACKAGE_GATSBY_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_GATSBY_CLI_NAME}
      - NODE_INSTALL_PACKAGE_GATSBY_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_GATSBY_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_HUSKY_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_HUSKY_NAME}
      - NODE_INSTALL_PACKAGE_HUSKY_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_HUSKY_VERSION}
      - NODE_CONFIG_PACKAGE_HYGEN_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_HYGEN_NAME}
      - NODE_INSTALL_PACKAGE_HYGEN_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_HYGEN_VERSION}
      - NODE_CONFIG_PACKAGE_IONIC_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_IONIC_CLI_NAME}
      - NODE_INSTALL_PACKAGE_IONIC_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_IONIC_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_KNEX_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_KNEX_NAME}
      - NODE_INSTALL_PACKAGE_KNEX_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_KNEX_VERSION}
      - NODE_CONFIG_PACKAGE_LINT_STAGED_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_LINT_STAGED_NAME}
      - NODE_INSTALL_PACKAGE_LINT_STAGED_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_LINT_STAGED_VERSION}
      - NODE_CONFIG_PACKAGE_LOOPBACK_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_LOOPBACK_CLI_NAME}
      - NODE_INSTALL_PACKAGE_LOOPBACK_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_LOOPBACK_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_NESTJS_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_NESTJS_CLI_NAME}
      - NODE_INSTALL_PACKAGE_NESTJS_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_NESTJS_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_NEWMAN_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_NEWMAN_NAME}
      - NODE_INSTALL_PACKAGE_NEWMAN_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_NEWMAN_VERSION}
      - NODE_CONFIG_PACKAGE_NRWL_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_NRWL_CLI_NAME}
      - NODE_INSTALL_PACKAGE_NRWL_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_NRWL_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_NRWL_TAO_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_NRWL_TAO_NAME}
      - NODE_INSTALL_PACKAGE_NRWL_TAO_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_NRWL_TAO_VERSION}
      - NODE_CONFIG_PACKAGE_NX_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_NX_NAME}
      - NODE_INSTALL_PACKAGE_NX_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_NX_VERSION}
      - NODE_CONFIG_PACKAGE_PNPM_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_PNPM_NAME}
      - NODE_INSTALL_PACKAGE_PNPM_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_PNPM_VERSION}
      - NODE_CONFIG_PACKAGE_PRETTIER_ESLINT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_PRETTIER_ESLINT_NAME}
      - NODE_INSTALL_PACKAGE_PRETTIER_ESLINT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_PRETTIER_ESLINT_VERSION}
      - NODE_CONFIG_PACKAGE_PRETTIER_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_PRETTIER_NAME}
      - NODE_INSTALL_PACKAGE_PRETTIER_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_PRETTIER_VERSION}
      - NODE_CONFIG_PACKAGE_PURESCRIPT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_PURESCRIPT_NAME}
      - NODE_INSTALL_PACKAGE_PURESCRIPT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_PURESCRIPT_VERSION}
      - NODE_CONFIG_PACKAGE_QUASAR_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_QUASAR_CLI_NAME}
      - NODE_INSTALL_PACKAGE_QUASAR_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_QUASAR_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_REACT_SCRIPTS_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_REACT_SCRIPTS_NAME}
      - NODE_INSTALL_PACKAGE_REACT_SCRIPTS_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_REACT_SCRIPTS_VERSION}
      - NODE_CONFIG_PACKAGE_REACT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_REACT_NAME}
      - NODE_INSTALL_PACKAGE_REACT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_REACT_VERSION}
      - NODE_CONFIG_PACKAGE_RESTIFY_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_RESTIFY_NAME}
      - NODE_INSTALL_PACKAGE_RESTIFY_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_RESTIFY_VERSION}
      - NODE_CONFIG_PACKAGE_SAILS_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_SAILS_NAME}
      - NODE_INSTALL_PACKAGE_SAILS_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_SAILS_VERSION}
      - NODE_CONFIG_PACKAGE_SASS_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_SASS_NAME}
      - NODE_INSTALL_PACKAGE_SASS_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_SASS_VERSION}
      - NODE_CONFIG_PACKAGE_SEQUELIZE_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_SEQUELIZE_NAME}
      - NODE_INSTALL_PACKAGE_SEQUELIZE_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_SEQUELIZE_VERSION}
      - NODE_CONFIG_PACKAGE_SPAGO_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_SPAGO_NAME}
      - NODE_INSTALL_PACKAGE_SPAGO_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_SPAGO_VERSION}
      - NODE_CONFIG_PACKAGE_TS_NODE_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_TS_NODE_NAME}
      - NODE_INSTALL_PACKAGE_TS_NODE_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_TS_NODE_VERSION}
      - NODE_CONFIG_PACKAGE_TYPESCRIPT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_TYPESCRIPT_NAME}
      - NODE_INSTALL_PACKAGE_TYPESCRIPT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_TYPESCRIPT_VERSION}
      - NODE_CONFIG_PACKAGE_TYPES_FILESYSTEM_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_TYPES_FILESYSTEM_NAME}
      - NODE_INSTALL_PACKAGE_TYPES_FILESYSTEM_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_TYPES_FILESYSTEM_VERSION}
      - NODE_CONFIG_PACKAGE_TYPES_NODE_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_TYPES_NODE_NAME}
      - NODE_INSTALL_PACKAGE_TYPES_NODE_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_TYPES_NODE_VERSION}
      - NODE_CONFIG_PACKAGE_VUE_CLI_PLUGIN_BABEL_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_VUE_CLI_PLUGIN_BABEL_NAME}
      - NODE_INSTALL_PACKAGE_VUE_CLI_PLUGIN_BABEL_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_VUE_CLI_PLUGIN_BABEL_VERSION}
      - NODE_CONFIG_PACKAGE_VUE_CLI_PLUGIN_ESLINT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_VUE_CLI_PLUGIN_ESLINT_NAME}
      - NODE_INSTALL_PACKAGE_VUE_CLI_PLUGIN_ESLINT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_VUE_CLI_PLUGIN_ESLINT_VERSION}
      - NODE_CONFIG_PACKAGE_VUE_CLI_SERVICE_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_VUE_CLI_SERVICE_NAME}
      - NODE_INSTALL_PACKAGE_VUE_CLI_SERVICE_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_VUE_CLI_SERVICE_VERSION}
      - NODE_CONFIG_PACKAGE_VUE_CLI_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_VUE_CLI_NAME}
      - NODE_INSTALL_PACKAGE_VUE_CLI_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_VUE_CLI_VERSION}
      - NODE_CONFIG_PACKAGE_YARN_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_YARN_NAME}
      - NODE_INSTALL_PACKAGE_YARN_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_YARN_VERSION}
      - NODE_CONFIG_PACKAGE_YO_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_YO_NAME}
      - NODE_INSTALL_PACKAGE_YO_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_YO_VERSION}
      - NODE_CONFIG_PACKAGE_NATIVE_RUN_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_NATIVE_RUN_NAME}
      - NODE_INSTALL_PACKAGE_NATIVE_RUN_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_NATIVE_RUN_VERSION}
      - NODE_CONFIG_PACKAGE_PLAYWRIGHT_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_PLAYWRIGHT_NAME}
      - NODE_INSTALL_PACKAGE_PLAYWRIGHT_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_PLAYWRIGHT_VERSION}
      - NODE_CONFIG_PACKAGE_GITLAB_CI_LOCAL_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_GITLAB_CI_LOCAL_NAME}
      - NODE_INSTALL_PACKAGE_GITLAB_CI_LOCAL_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_GITLAB_CI_LOCAL_VERSION}
      - NODE_CONFIG_PACKAGE_ZOD_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_ZOD_NAME}
      - NODE_INSTALL_PACKAGE_ZOD_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_ZOD_VERSION}
      - NODE_CONFIG_PACKAGE_HONO_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_HONO_NAME}
      - NODE_INSTALL_PACKAGE_HONO_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_HONO_VERSION}
      - NODE_CONFIG_PACKAGE_SERVERLESS_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_SERVERLESS_NAME}
      - NODE_INSTALL_PACKAGE_SERVERLESS_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_SERVERLESS_VERSION}
      - NODE_CONFIG_PACKAGE_VITE_NAME=${GLOBAL_STACK_NODEEDGE_CONFIG_PACKAGE_VITE_NAME}
      - NODE_INSTALL_PACKAGE_VITE_VERSION=${GLOBAL_STACK_NODEEDGE_INSTALL_PACKAGE_VITE_VERSION}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - CURL_CA_BUNDLE=${GLOBAL_STACK_BASE_CURL_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
      - GLOBAL_STACK_DOCKER_USER_EMAIL=${GLOBAL_STACK_DOCKER_USER_EMAIL}
      - GLOBAL_STACK_DOCKER_USER_NAME=${GLOBAL_STACK_DOCKER_USER_NAME}
      - GLOBAL_STACK_ERROR_TOKEN=node.${GLOBAL_STACK_NODEEDGE_VERSION_AS}
    image: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}/local_global_stack_03nodeedge:${GLOBAL_STACK_VERSION}
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "! test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_ERRORS}/node.${GLOBAL_STACK_NODEEDGE_VERSION_AS} && test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}/node.${GLOBAL_STACK_NODEEDGE_VERSION_AS} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 99999
      start_period: 24h
    labels:
      stack.service: "03nodeedge"
      stack.tier: "runtime"
      stack.version: "${GLOBAL_STACK_VERSION}"
    privileged: true
    restart: "on-failure:5"
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - ./docker/config/dist/conf:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/conf:rw
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
