networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${GLOBAL_STACK_HOST_GATEWAY_IP_MASK}
        gateway: ${GLOBAL_STACK_HOST_GATEWAY_IP}

# Additional services can be defined in docker/images/**
# Activate or deactivate specific images by using the COMPOSE_FILE variable 
# in your .env or .env.local configuration files.
