---
services:
  05edge:
    extends:
      file: docker/config/compose-fragments/base.compose.yaml
      service: base
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
        GLOBAL_STACK_ANDROID_LOCALE: ${GLOBAL_STACK_ANDROID_LOCALE}
        GLOBAL_STACK_ANDROID_SET_LOCALE: ${GLOBAL_STACK_ANDROID_SET_LOCALE}
      context: ./
      dockerfile: ./docker/images/05edge/Dockerfile
    depends_on:
      00base:
        condition: service_healthy
        required: true
      02phpbrew:
        condition: service_healthy
        required: true
      02nvm:
        condition: service_healthy
        required: true
      02fvm:
        condition: service_healthy
        required: true
      02sdkman:
        condition: service_healthy
        required: true
      02pyenv:
        condition: service_healthy
        required: true
      02rust:
        condition: service_healthy
        required: true
      03phpedge:
        condition: service_healthy
        required: true
      03nodeedge:
        condition: service_healthy
        required: true
      03flutter3:
        condition: service_healthy
        required: true
      03java26-zulu:
        condition: service_healthy
        required: true
      03ruby4:
        condition: service_healthy
        required: true
      03python3:
        condition: service_healthy
        required: true
      04android:
        condition: service_healthy
        required: true
    environment:
      - ALLTOGETHER_NAME=edge
      - PYENV_ROOT=${GLOBAL_STACK_PYENV_ROOT}
      - PYTHON_VERSION=${GLOBAL_STACK_PYTHON3_VERSION}
      - PYTHON_VERSION_AS=${GLOBAL_STACK_PYTHON3_VERSION_AS}
      - GLOBAL_STACK_PYTHON_STABLE=${GLOBAL_STACK_PYTHON3_STABLE}
      - DENO_INSTALL=${GLOBAL_STACK_DENO_INSTALL}
      - DENO_INSTALL_ROOT=${GLOBAL_STACK_DENO_INSTALL_ROOT}
      - DENO_DIR=${GLOBAL_STACK_DENO_DIR}
      - BUN_INSTALL=${GLOBAL_STACK_BUN_INSTALL}
      - NVM_DIR=${GLOBAL_STACK_NVM_DIR}
      - YARN_OFFLINE_MIRROR=${GLOBAL_STACK_YARN_OFFLINE_MIRROR}
      - YARN_CACHE_FOLDER=${GLOBAL_STACK_YARN_CACHE_FOLDER}
      - YARN_GLOBAL_FOLDER=${GLOBAL_STACK_YARN_GLOBAL_FOLDER}
      - GLOBAL_STACK_PNPM_GLOBAL_DIR=${GLOBAL_STACK_PNPM_GLOBAL_DIR}
      - PNPM_HOME=${GLOBAL_STACK_PNPM_GLOBAL_DIR}
      - GLOBAL_STACK_PNPM_STORE_DIR=${GLOBAL_STACK_PNPM_STORE_DIR}
      - NPM_CACHE_DIR=${GLOBAL_STACK_NPM_CACHE_DIR}
      - CYPRESS_CACHE_FOLDER=${GLOBAL_STACK_CYPRESS_CACHE_FOLDER}
      - NODE_VERSION_AS=${GLOBAL_STACK_NODEEDGE_VERSION_AS}
      - NODE_VERSION=${GLOBAL_STACK_NODEEDGE_VERSION}
      - SDKMAN_DIR=${GLOBAL_STACK_SDKMAN_DIR}
      - JAVA_VERSION_AS=${GLOBAL_STACK_JAVA26_VERSION_AS}
      - JAVA_VERSION=${GLOBAL_STACK_JAVA26_VERSION}
      - SDKMAN_CONFIG_PACKAGE_DUMMY_NAME=dummy
      - SDKMAN_INSTALL_PACKAGE_DUMMY_VERSION=0
      - SDKMAN_CONFIG_PACKAGE_01_ANT_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_ANT_NAME}
      - SDKMAN_INSTALL_PACKAGE_01_ANT_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_ANT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_02_GRADLE_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_GRADLE_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_02_GRADLE_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_GRADLE_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_03_KOTLIN_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_KOTLIN_NAME}
      - SDKMAN_INSTALL_PACKAGE_03_KOTLIN_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_KOTLIN_VERSION}
      - SDKMAN_CONFIG_PACKAGE_04_MAVEN_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_MAVEN_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_04_MAVEN_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_MAVEN_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_05_POMCHECKER_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_POMCHECKER_NAME}
      - SDKMAN_INSTALL_PACKAGE_05_POMCHECKER_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_POMCHECKER_VERSION}
      - SDKMAN_CONFIG_PACKAGE_06_SPRINGBOOT_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_SPRINGBOOT_NAME}
      - SDKMAN_INSTALL_PACKAGE_06_SPRINGBOOT_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_SPRINGBOOT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_07_TOMCAT_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_TOMCAT_NAME}
      - SDKMAN_INSTALL_PACKAGE_07_TOMCAT_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_TOMCAT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_08_GROOVY_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_GROOVY_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_08_GROOVY_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_GROOVY_VX2_VERSION}
      - SDKMAN_CONFIG_PACKAGE_09_MICRONAUT_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_MICRONAUT_NAME}
      - SDKMAN_INSTALL_PACKAGE_09_MICRONAUT_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_MICRONAUT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_10_QUARKUS_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_QUARKUS_NAME}
      - SDKMAN_INSTALL_PACKAGE_10_QUARKUS_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_QUARKUS_VERSION}
      - SDKMAN_CONFIG_PACKAGE_11_SPARK_NAME=${GLOBAL_STACK_JAVA_CONFIG_PACKAGE_SPARK_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_11_SPARK_VERSION=${GLOBAL_STACK_JAVA_INSTALL_PACKAGE_SPARK_VX2_VERSION}
      - RBENV_ROOT=${GLOBAL_STACK_RBENV_ROOT}
      - RUBY_CONFIG_PACKAGE_01_GOOGLE_API_CLIENT_NAME=${GLOBAL_STACK_RUBY_CONFIG_PACKAGE_GOOGLE_API_CLIENT_NAME}
      - RUBY_INSTALL_PACKAGE_01_GOOGLE_API_CLIENT_VERSION=${GLOBAL_STACK_RUBY_INSTALL_PACKAGE_GOOGLE_API_CLIENT_VERSION}
      - RUBY_CONFIG_PACKAGE_02_FASTLANE_NAME=${GLOBAL_STACK_RUBY_CONFIG_PACKAGE_FASTLANE_NAME}
      - RUBY_INSTALL_PACKAGE_02_FASTLANE_VERSION=${GLOBAL_STACK_RUBY_INSTALL_PACKAGE_FASTLANE_VERSION}
      - RUBY_VERSION=${GLOBAL_STACK_RUBY4_VERSION}
      - RUBY_VERSION_AS=${GLOBAL_STACK_RUBY4_VERSION_AS}
      - PHPBREW_BIN=${GLOBAL_STACK_PHPBREW_BIN}
      - PHPBREW_HOME=${GLOBAL_STACK_PHPBREW_HOME}
      - PHPBREW_ROOT=${GLOBAL_STACK_PHPBREW_ROOT}
      - PHPBREW_SRC=${GLOBAL_STACK_PHPBREW_SRC}
      - PHPBREW_SET_PROMPT=${GLOBAL_STACK_PHPBREW_SET_PROMPT}
      - PHPBREW_SKIP_INIT=${GLOBAL_STACK_PHPBREW_SKIP_INIT}
      - PHPBREW_RC_ENABLE=${GLOBAL_STACK_PHPBREW_RC_ENABLE}
      - COMPOSER_HOME=${GLOBAL_STACK_COMPOSER_HOME}
      - COMPOSER_SOURCE=${GLOBAL_STACK_COMPOSER_SOURCE}
      - SYMFONY_HOME=${GLOBAL_STACK_SYMFONY_HOME}
      - PHP_VERSION=${GLOBAL_STACK_PHPEDGE_VERSION}
      - PHP_VERSION_AS=${GLOBAL_STACK_PHPEDGE_VERSION_AS}
      - RUSTUP_HOME=${GLOBAL_STACK_RUSTUP_HOME}
      - CARGO_HOME=${GLOBAL_STACK_CARGO_HOME}
      - GLOBAL_STACK_ANDROID_BUILD_TOOLS_VERSION=${GLOBAL_STACK_ANDROID_BUILD_TOOLS_VERSION}
      - GLOBAL_STACK_ANDROID_CMDLINE_TOOLS_VERSION=${GLOBAL_STACK_ANDROID_CMDLINE_TOOLS_VERSION}
      - GLOBAL_STACK_ANDROID_INSTALL_SYSTEM_IMAGES=${GLOBAL_STACK_ANDROID_INSTALL_SYSTEM_IMAGES}
      - GLOBAL_STACK_ANDROID_NDK_VERSION=${GLOBAL_STACK_ANDROID_NDK_VERSION}
      - GLOBAL_STACK_ANDROID_NDK_BUNDLE_VERSION=${GLOBAL_STACK_ANDROID_NDK_BUNDLE_VERSION}
      - GLOBAL_STACK_ANDROID_PLATFORM_TOOLS_VERSION=${GLOBAL_STACK_ANDROID_PLATFORM_TOOLS_VERSION}
      - GLOBAL_STACK_ANDROID_SDK_URL=${GLOBAL_STACK_ANDROID_SDK_URL}
      - ANDROID_HOME=${GLOBAL_STACK_ANDROID_HOME}
      - ANDROID_SDK_ROOT=${GLOBAL_STACK_ANDROID_SDK_ROOT}
      - ANDROID_SDK_HOME=${GLOBAL_STACK_ANDROID_SDK_HOME}
      - ANDROID_NDK_HOME=${GLOBAL_STACK_ANDROID_NDK_HOME}
      - GRADLE_USER_HOME=${GLOBAL_STACK_GRADLE_USER_HOME}
      - FLUTTER_VERSION=${GLOBAL_STACK_FLUTTER3_VERSION}
      - FLUTTER_VERSION_AS=${GLOBAL_STACK_FLUTTER3_VERSION_AS}
      - FLUTTER_ROOT=${GLOBAL_STACK_FLUTTER3_ROOT}
      - FLUTTER_HOME=${GLOBAL_STACK_FLUTTER3_HOME}
      - FVM_CACHE_PATH=${GLOBAL_STACK_FVM_CACHE_PATH}
      - FVM_USE_GIT_CACHE=${GLOBAL_STACK_FVM_USE_GIT_CACHE}
      - FVM_GIT_CACHE_PATH=${GLOBAL_STACK_FVM_GIT_CACHE_PATH}
      - FVM_FLUTTER_URL=${GLOBAL_STACK_FVM_FLUTTER_URL}
      - PUB_CACHE=${GLOBAL_STACK_PUB_CACHE}
      - ANDROID_ADB_SERVER_ADDRESS=${GLOBAL_STACK_DOCKER_HOST_DSN}
      - GLOBAL_STACK_WAIT_FOR_TIMEOUT=${GLOBAL_STACK_WAIT_FOR_TIMEOUT}
      - GLOBAL_STACK_ERROR_TOKEN=${GLOBAL_STACK_05EDGE_ALLTOGETHER_NAME}
    healthcheck:
      test: ["CMD-SHELL", "! test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_ERRORS}/${GLOBAL_STACK_05EDGE_ALLTOGETHER_NAME} && test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}/${GLOBAL_STACK_05EDGE_ALLTOGETHER_NAME} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 99999
      start_period: 24h
    labels:
      stack.service: "05edge"
      stack.tier: "dev"
      stack.version: "${GLOBAL_STACK_VERSION}"
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}/
    volumes:
      - 05edge_lib_docker:/var/lib/docker:rw,delegated
volumes:
  05edge_lib_docker:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_05edge_lib_docker
