---
services:
  01mongo8:
    init: ${DOCKER_INIT}
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_SHELL_HISTORY: ${GLOBAL_STACK_SHELL_HISTORY}
        GLOBAL_STACK_IMAGE_MONGO8_VERSION: ${GLOBAL_STACK_IMAGE_MONGO8_VERSION}
      context: ./
      dockerfile: ./docker/images/01mongo8/Dockerfile
    environment:
      - MONGO_DBS=${GLOBAL_STACK_MONGO8_DBS}
      - MONGODB_PASSWORD=${GLOBAL_STACK_DATABASE_ROOT_PASSWORD}
      - MONGODB_USER=root
      - TZ=${GLOBAL_STACK_TIMEZONE}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - public
    ports:
      - ${GLOBAL_STACK_MONGO8_PORT_27017:-}27017
    labels:
      stack.service: "01mongo8"
      stack.tier: "database"
      stack.version: "${GLOBAL_STACK_VERSION}"
    restart: "on-failure:5"
    volumes:
      - ./docker/data/dumps/mongo/8:/opt/dumps:rw
      - 01mongo8_data:/data/db:rw,delegated
      - 01mongo8_configdb:/data/configdb:rw,delegated
        # - ./var/database-history/mongosh_repl_history:/data/db/.mongodb/mongosh/mongosh_repl_history:rw,delegated
        # - source: ./docker/logs/mongodb/8
        #   target: /var/log/mongodb
        #   type: bind
volumes:
  01mongo8_data:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_01mongo8_data
  01mongo8_configdb:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_01mongo8_configdb
