---
services:
  03java11-zulu:
    init: true
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/03java11-zulu/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - 00base
      - 02sdkman
    extra_hosts:
      - ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    environment:
      - SDKMAN_MODE=setup
      - GLOBAL_STACK_SDKMAN_VERSION=${GLOBAL_STACK_SDKMAN_VERSION}
      - SDKMAN_DIR=${GLOBAL_STACK_SDKMAN_DIR}
      - JAVA_VERSION_AS=11
      - JAVA_VERSION=${GLOBAL_STACK_JAVA11_VERSION}
      - SDKMAN_CONFIG_PACKAGE_DUMMY_NAME=dummy
      - SDKMAN_INSTALL_PACKAGE_DUMMY_VERSION=0
      - SDKMAN_CONFIG_PACKAGE_01_ANT_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_ANT_NAME}
      - SDKMAN_INSTALL_PACKAGE_01_ANT_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_ANT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_02_GRADLE_VX1_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_GRADLE_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_02_GRADLE_VX1_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_GRADLE_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_02_GRADLE_VX2_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_GRADLE_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_02_GRADLE_VX2_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_GRADLE_VX2_VERSION}
      - SDKMAN_CONFIG_PACKAGE_03_KOTLIN_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_KOTLIN_NAME}
      - SDKMAN_INSTALL_PACKAGE_03_KOTLIN_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_KOTLIN_VERSION}
      - SDKMAN_CONFIG_PACKAGE_04_MAVEN_VX1_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_MAVEN_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_04_MAVEN_VX1_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_MAVEN_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_04_MAVEN_VX2_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_MAVEN_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_04_MAVEN_VX2_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_MAVEN_VX2_VERSION}
      - SDKMAN_CONFIG_PACKAGE_04_MAVEN_VX3_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_MAVEN_VX3_NAME}
      - SDKMAN_INSTALL_PACKAGE_04_MAVEN_VX3_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_MAVEN_VX3_VERSION}
      - SDKMAN_CONFIG_PACKAGE_05_POMCHECKER_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_POMCHECKER_NAME}
      - SDKMAN_INSTALL_PACKAGE_05_POMCHECKER_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_POMCHECKER_VERSION}
      - SDKMAN_CONFIG_PACKAGE_06_SPRINGBOOT_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_SPRINGBOOT_NAME}
      - SDKMAN_INSTALL_PACKAGE_06_SPRINGBOOT_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_SPRINGBOOT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_07_TOMCAT_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_TOMCAT_NAME}
      - SDKMAN_INSTALL_PACKAGE_07_TOMCAT_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_TOMCAT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_08_GROOVY_VX1_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_GROOVY_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_08_GROOVY_VX1_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_GROOVY_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_08_GROOVY_VX2_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_GROOVY_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_08_GROOVY_VX2_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_GROOVY_VX2_VERSION}
      - SDKMAN_CONFIG_PACKAGE_09_MICRONAUT_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_MICRONAUT_NAME}
      - SDKMAN_INSTALL_PACKAGE_09_MICRONAUT_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_MICRONAUT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_10_QUARKUS_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_QUARKUS_NAME}
      - SDKMAN_INSTALL_PACKAGE_10_QUARKUS_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_QUARKUS_VERSION}
      - SDKMAN_CONFIG_PACKAGE_11_SPARK_VX1_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_SPARK_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_11_SPARK_VX1_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_SPARK_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_11_SPARK_VX2_NAME=${GLOBAL_STACK_JAVA11_CONFIG_PACKAGE_SPARK_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_11_SPARK_VX2_VERSION=${GLOBAL_STACK_JAVA11_INSTALL_PACKAGE_SPARK_VX2_VERSION}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - CURL_CA_BUNDLE=${GLOBAL_STACK_BASE_CURL_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    image: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}/local_global_stack_03java11-zulu:${GLOBAL_STACK_VERSION}
    networks:
      - public
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - ./docker/config/dist/conf:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/conf:rw
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
