---
services:
  03php8-4:
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/03php8-4/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - 00base
      - 02phpbrew
    extra_hosts:
      - ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    environment:
      - PHPBREW_MODE=setup
      - GLOBAL_STACK_COMPOSER_VERSION=${GLOBAL_STACK_COMPOSER_VERSION}
      - GLOBAL_STACK_DEPLOYER_VERSION=${GLOBAL_STACK_DEPLOYER_VERSION}
      - GLOBAL_STACK_FABPOT_LOCAL_PHP_SECURITY_CHECKER_VERSION=${GLOBAL_STACK_FABPOT_LOCAL_PHP_SECURITY_CHECKER_VERSION}
      - GLOBAL_STACK_FRANKENPHP_VERSION=${GLOBAL_STACK_FRANKENPHP_VERSION}
      - GLOBAL_STACK_PHALCON_DEVTOOLS_VERSION=${GLOBAL_STACK_PHALCON_DEVTOOLS_VERSION}
      - GLOBAL_STACK_PHPBREW_VERSION=${GLOBAL_STACK_PHPBREW_VERSION}
      - GLOBAL_STACK_PICKLE_VERSION=${GLOBAL_STACK_PICKLE_VERSION}
      - GLOBAL_STACK_RELOAD_PHPBREW=${GLOBAL_STACK_RELOAD_PHPBREW}
      - GLOBAL_STACK_SYMFONY_CLI_VERSION=${GLOBAL_STACK_SYMFONY_CLI_VERSION}
      - GLOBAL_STACK_ZEPHIR_LANG_VERSION=${GLOBAL_STACK_ZEPHIR_LANG_VERSION}
      - PHPBREW_BIN=${GLOBAL_STACK_PHPBREW_BIN}
      - PHPBREW_HOME=${GLOBAL_STACK_PHPBREW_HOME}
      - PHPBREW_ROOT=${GLOBAL_STACK_PHPBREW_ROOT}
      - PHPBREW_SRC=${GLOBAL_STACK_PHPBREW_SRC}
      - PHPBREW_SET_PROMPT=${GLOBAL_STACK_PHPBREW_SET_PROMPT}
      - PHPBREW_SKIP_INIT=${GLOBAL_STACK_PHPBREW_SKIP_INIT}
      - PHPBREW_RC_ENABLE=${GLOBAL_STACK_PHPBREW_RC_ENABLE}
      - COMPOSER_HOME=${GLOBAL_STACK_COMPOSER_HOME}
      - COMPOSER_SOURCE=${GLOBAL_STACK_COMPOSER_SOURCE}
      - SYMFONY_HOME=${GLOBAL_STACK_SYMFONY_HOME}
      - PHP_VERSION=${GLOBAL_STACK_PHP8_4_VERSION}
      - PHP_VERSION_AS=8.4
      - PHP_CONFIG_PACKAGE_01_XML_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_XML_NAME}
      - PHP_CONFIG_PACKAGE_01_XML_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_XML_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_01_XML_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_XML_VERSION}
      - PHP_CONFIG_PACKAGE_02_EXIF_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_EXIF_NAME}
      - PHP_CONFIG_PACKAGE_02_EXIF_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_EXIF_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_02_EXIF_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_EXIF_VERSION}
      - PHP_CONFIG_PACKAGE_03_FTP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_FTP_NAME}
      - PHP_CONFIG_PACKAGE_03_FTP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_FTP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_03_FTP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_FTP_VERSION}
      - PHP_CONFIG_PACKAGE_04_GD_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_GD_NAME}
      - PHP_CONFIG_PACKAGE_04_GD_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_GD_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_04_GD_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_GD_VERSION}
      - PHP_CONFIG_PACKAGE_05_GETTEXT_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_GETTEXT_NAME}
      - PHP_CONFIG_PACKAGE_05_GETTEXT_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_GETTEXT_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_05_GETTEXT_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_GETTEXT_VERSION}
      - PHP_CONFIG_PACKAGE_06_GMP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_GMP_NAME}
      - PHP_CONFIG_PACKAGE_06_GMP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_GMP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_06_GMP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_GMP_VERSION}
      - PHP_CONFIG_PACKAGE_07_ICONV_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_ICONV_NAME}
      - PHP_CONFIG_PACKAGE_07_ICONV_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_ICONV_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_07_ICONV_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_ICONV_VERSION}
      - PHP_CONFIG_PACKAGE_08_INTL_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_INTL_NAME}
      - PHP_CONFIG_PACKAGE_08_INTL_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_INTL_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_08_INTL_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_INTL_VERSION}
      - PHP_CONFIG_PACKAGE_09_LDAP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_LDAP_NAME}
      - PHP_CONFIG_PACKAGE_09_LDAP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_LDAP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_09_LDAP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_LDAP_VERSION}
      - PHP_CONFIG_PACKAGE_10_MEMCACHE_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_MEMCACHE_NAME}
      - PHP_CONFIG_PACKAGE_10_MEMCACHE_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_MEMCACHE_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_10_MEMCACHE_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_MEMCACHE_VERSION}
      - PHP_CONFIG_PACKAGE_11_OPCACHE_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_OPCACHE_NAME}
      - PHP_CONFIG_PACKAGE_11_OPCACHE_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_OPCACHE_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_11_OPCACHE_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_OPCACHE_VERSION}
      - PHP_CONFIG_PACKAGE_12_SOAP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_SOAP_NAME}
      - PHP_CONFIG_PACKAGE_12_SOAP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_SOAP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_12_SOAP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_SOAP_VERSION}
      - PHP_CONFIG_PACKAGE_13_ZMQ_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_ZMQ_NAME}
      - PHP_CONFIG_PACKAGE_13_ZMQ_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_ZMQ_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_13_ZMQ_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_ZMQ_VERSION}
      - PHP_CONFIG_PACKAGE_14_AMQP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_AMQP_NAME}
      - PHP_CONFIG_PACKAGE_14_AMQP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_AMQP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_14_AMQP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_AMQP_VERSION}
      - PHP_CONFIG_PACKAGE_15_APCU_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_APCU_NAME}
      - PHP_CONFIG_PACKAGE_15_APCU_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_APCU_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_15_APCU_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_APCU_VERSION}
      - PHP_CONFIG_PACKAGE_16_IMAGICK_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_IMAGICK_NAME}
      - PHP_CONFIG_PACKAGE_16_IMAGICK_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_IMAGICK_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_16_IMAGICK_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_IMAGICK_VERSION}
      - PHP_CONFIG_PACKAGE_17_INOTIFY_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_INOTIFY_NAME}
      - PHP_CONFIG_PACKAGE_17_INOTIFY_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_INOTIFY_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_17_INOTIFY_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_INOTIFY_VERSION}
      - PHP_CONFIG_PACKAGE_18_MEMCACHED_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_MEMCACHED_NAME}
      - PHP_CONFIG_PACKAGE_18_MEMCACHED_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_MEMCACHED_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_18_MEMCACHED_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_MEMCACHED_VERSION}
      - PHP_CONFIG_PACKAGE_19_MONGODB_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_MONGODB_NAME}
      - PHP_CONFIG_PACKAGE_19_MONGODB_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_MONGODB_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_19_MONGODB_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_MONGODB_VERSION}
      - PHP_CONFIG_PACKAGE_20_PROPRO_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PROPRO_NAME}
      - PHP_CONFIG_PACKAGE_20_PROPRO_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PROPRO_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_20_PROPRO_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_PROPRO_VERSION}
      - PHP_CONFIG_PACKAGE_21_RAPHF_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_RAPHF_NAME}
      - PHP_CONFIG_PACKAGE_21_RAPHF_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_RAPHF_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_21_RAPHF_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_RAPHF_VERSION}
      - PHP_CONFIG_PACKAGE_22_PECL_HTTP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PECL_HTTP_NAME}
      - PHP_CONFIG_PACKAGE_22_PECL_HTTP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PECL_HTTP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_22_PECL_HTTP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_PECL_HTTP_VERSION}
      - PHP_CONFIG_PACKAGE_23_PSR_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PSR_NAME}
      - PHP_CONFIG_PACKAGE_23_PSR_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PSR_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_23_PSR_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_PSR_VERSION}
      - PHP_CONFIG_PACKAGE_24_REDIS_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_REDIS_NAME}
      - PHP_CONFIG_PACKAGE_24_REDIS_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_REDIS_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_24_REDIS_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_REDIS_VERSION}
      - PHP_CONFIG_PACKAGE_25_SSH2_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_SSH2_NAME}
      - PHP_CONFIG_PACKAGE_25_SSH2_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_SSH2_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_25_SSH2_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_SSH2_VERSION}
      - PHP_CONFIG_PACKAGE_26_SWOOLE_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_SWOOLE_NAME}
      - PHP_CONFIG_PACKAGE_26_SWOOLE_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_SWOOLE_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_26_SWOOLE_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_SWOOLE_VERSION}
      - PHP_CONFIG_PACKAGE_27_TIMECOP_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_TIMECOP_NAME}
      - PHP_CONFIG_PACKAGE_27_TIMECOP_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_TIMECOP_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_27_TIMECOP_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_TIMECOP_VERSION}
      - PHP_CONFIG_PACKAGE_28_UUID_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_UUID_NAME}
      - PHP_CONFIG_PACKAGE_28_UUID_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_UUID_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_28_UUID_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_UUID_VERSION}
      - PHP_CONFIG_PACKAGE_29_XDEBUG_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_XDEBUG_NAME}
      - PHP_CONFIG_PACKAGE_29_XDEBUG_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_XDEBUG_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_29_XDEBUG_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_XDEBUG_VERSION}
      - PHP_CONFIG_PACKAGE_30_YAML_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_YAML_NAME}
      - PHP_CONFIG_PACKAGE_30_YAML_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_YAML_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_30_YAML_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_YAML_VERSION}
      - PHP_CONFIG_PACKAGE_31_ZEPHIR_PARSER_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_ZEPHIR_PARSER_NAME}
      - PHP_CONFIG_PACKAGE_31_ZEPHIR_PARSER_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_ZEPHIR_PARSER_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_31_ZEPHIR_PARSER_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_ZEPHIR_PARSER_VERSION}
      - PHP_CONFIG_PACKAGE_32_PHALCON_NAME=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PHALCON_NAME}
      - PHP_CONFIG_PACKAGE_32_PHALCON_COMMAND_SUFFIX=${GLOBAL_STACK_PHP8_4_CONFIG_PACKAGE_PHALCON_COMMAND_SUFFIX}
      - PHP_INSTALL_PACKAGE_32_PHALCON_VERSION=${GLOBAL_STACK_PHP8_4_INSTALL_PACKAGE_PHALCON_VERSION}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    image: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}/local_global_stack_03php8-4:${GLOBAL_STACK_VERSION}
    networks:
      - public
    ports:
      - ${GLOBAL_STACK_PHP8_4_PORT_9001:-}9001
      - ${GLOBAL_STACK_PHP8_4_FRANKENPHP_PORT_8080:-}8080
      - ${GLOBAL_STACK_PHP8_4_FRANKENPHP_PORT_8443:-}8443
    privileged: true
    restart: unless-stopped
    volumes:
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - ./docker/config/dist/conf:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/conf:rw
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
