---
services:
  03python3:
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/03python3/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - 00base
      - 02pyenv
    extra_hosts:
      - ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    environment:
      - PYENV_MODE=setup
      - GLOBAL_STACK_PYENV_VERSION=${GLOBAL_STACK_PYENV_VERSION}
      - GLOBAL_STACK_PYTHON_STABLE=${GLOBAL_STACK_PYTHON_STABLE}
      - GLOBAL_STACK_RELOAD_PYENV=${GLOBAL_STACK_RELOAD_PYENV}
      - PYENV_ROOT=${GLOBAL_STACK_PYENV_ROOT}
      - PYTHON_VERSION=${GLOBAL_STACK_PYTHON3_VERSION}
      - PYTHON_VERSION_AS=3
      - GLOBAL_STACK_PYTHON_STABLE=${GLOBAL_STACK_PYTHON3_STABLE}
      - PYTHON_CONFIG_PACKAGE_01_PIP_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_PIP_NAME}
      - PYTHON_INSTALL_PACKAGE_01_PIP_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_PIP_VERSION}
      - PYTHON_CONFIG_PACKAGE_02_PYYAML_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_PYYAML_NAME}
      - PYTHON_INSTALL_PACKAGE_02_PYYAML_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_PYYAML_VERSION}
      - PYTHON_CONFIG_PACKAGE_03_BLINKER_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_BLINKER_NAME}
      - PYTHON_INSTALL_PACKAGE_03_BLINKER_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_BLINKER_VERSION}
      - PYTHON_CONFIG_PACKAGE_04_PIPENV_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_PIPENV_NAME}
      - PYTHON_INSTALL_PACKAGE_04_PIPENV_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_PIPENV_VERSION}
      - PYTHON_CONFIG_PACKAGE_05_SIMPLEJSON_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_SIMPLEJSON_NAME}
      - PYTHON_INSTALL_PACKAGE_05_SIMPLEJSON_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_SIMPLEJSON_VERSION}
      - PYTHON_CONFIG_PACKAGE_06_PYTHON_DOTENV_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_PYTHON_DOTENV_NAME}
      - PYTHON_INSTALL_PACKAGE_06_PYTHON_DOTENV_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_PYTHON_DOTENV_VERSION}
      - PYTHON_CONFIG_PACKAGE_07_WATCHDOG_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_WATCHDOG_NAME}
      - PYTHON_INSTALL_PACKAGE_07_WATCHDOG_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_WATCHDOG_VERSION}
      - PYTHON_CONFIG_PACKAGE_08_VIRTUALENV_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_VIRTUALENV_NAME}
      - PYTHON_INSTALL_PACKAGE_08_VIRTUALENV_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_VIRTUALENV_VERSION}
      - PYTHON_CONFIG_PACKAGE_09_PYLINT_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_PYLINT_NAME}
      - PYTHON_INSTALL_PACKAGE_09_PYLINT_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_PYLINT_VERSION}
      - PYTHON_CONFIG_PACKAGE_10_WHEEL_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_WHEEL_NAME}
      - PYTHON_INSTALL_PACKAGE_10_WHEEL_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_WHEEL_VERSION}
      - PYTHON_CONFIG_PACKAGE_11_PSYCOPG2_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_PSYCOPG2_NAME}
      - PYTHON_INSTALL_PACKAGE_11_PSYCOPG2_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_PSYCOPG2_VERSION}
      - PYTHON_CONFIG_PACKAGE_12_MYSQLCLIENT_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_MYSQLCLIENT_NAME}
      - PYTHON_INSTALL_PACKAGE_12_MYSQLCLIENT_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_MYSQLCLIENT_VERSION}
      - PYTHON_CONFIG_PACKAGE_13_SETUPTOOLS_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_SETUPTOOLS_NAME}
      - PYTHON_INSTALL_PACKAGE_13_SETUPTOOLS_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_SETUPTOOLS_VERSION}
      - PYTHON_CONFIG_PACKAGE_14_NATSORT_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_NATSORT_NAME}
      - PYTHON_INSTALL_PACKAGE_14_NATSORT_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_NATSORT_VERSION}
      - PYTHON_CONFIG_PACKAGE_15_ATTRDICT3_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_ATTRDICT3_NAME}
      - PYTHON_INSTALL_PACKAGE_15_ATTRDICT3_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_ATTRDICT3_VERSION}
      - PYTHON_CONFIG_PACKAGE_16_ATTRDICT_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_ATTRDICT_NAME}
      - PYTHON_INSTALL_PACKAGE_16_ATTRDICT_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_ATTRDICT_VERSION}
      - PYTHON_CONFIG_PACKAGE_17_WXPYTHON_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_WXPYTHON_NAME}
      - PYTHON_INSTALL_PACKAGE_17_WXPYTHON_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_WXPYTHON_VERSION}
      - PYTHON_CONFIG_PACKAGE_18_DJANGO_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_DJANGO_NAME}
      - PYTHON_INSTALL_PACKAGE_18_DJANGO_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_DJANGO_VERSION}
      - PYTHON_CONFIG_PACKAGE_19_FLASK_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_FLASK_NAME}
      - PYTHON_INSTALL_PACKAGE_19_FLASK_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_FLASK_VERSION}
      - PYTHON_CONFIG_PACKAGE_20_YAMLLINT_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_YAMLLINT_NAME}
      - PYTHON_INSTALL_PACKAGE_20_YAMLLINT_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_YAMLLINT_VERSION}
      - PYTHON_CONFIG_PACKAGE_21_UV_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_UV_NAME}
      - PYTHON_INSTALL_PACKAGE_21_UV_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_UV_VERSION}
      - PYTHON_CONFIG_PACKAGE_23_AWSCLI_LOCAL_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_AWSCLI_LOCAL_NAME}
      - PYTHON_INSTALL_PACKAGE_23_AWSCLI_LOCAL_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_AWSCLI_LOCAL_VERSION}
      - PYTHON_CONFIG_PACKAGE_24_FASTAPI_NAME=${GLOBAL_STACK_PYTHON3_CONFIG_PACKAGE_FASTAPI_NAME}
      - PYTHON_INSTALL_PACKAGE_24_FASTAPI_VERSION=${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_FASTAPI_VERSION}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    image: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}/local_global_stack_03python3:${GLOBAL_STACK_VERSION}
    networks:
      - public
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
