---
services:
  01postgres18:
    init: ${DOCKER_INIT}
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_SHELL_HISTORY: ${GLOBAL_STACK_SHELL_HISTORY}
        GLOBAL_STACK_IMAGE_POSTGRES18_VERSION: ${GLOBAL_STACK_IMAGE_POSTGRES18_VERSION}
      context: ./
      dockerfile: ./docker/images/01postgres18/Dockerfile
    environment:
      - POSTGRES_DBS=${GLOBAL_STACK_POSTGRES18_DBS}
      - POSTGRES_PASSWORD=${GLOBAL_STACK_DATABASE_ROOT_PASSWORD}
      - POSTGRES_USER=root
      - TZ=${GLOBAL_STACK_TIMEZONE}
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      stack.service: "01postgres18"
      stack.tier: "database"
      stack.version: "${GLOBAL_STACK_VERSION}"
    restart: "on-failure:5"
    shm_size: ${GLOBAL_STACK_POSTGRES18_SHM_SIZE:-1gb}
    ports:
      - ${GLOBAL_STACK_POSTGRES18_PORT_5432:-}5432
    volumes:
      - ./docker/data/dumps/postgres/18:/opt/dumps:rw
      - 01postgres18_var_lib_postgresql:/var/lib/postgresql:rw,delegated
        # - ./var/database-history/.psql_history:/root/.psql_history:rw,delegated
        # - source: ./docker/logs/postgresql/17
        #   target: /var/log/postgresql
        #   type: bind
volumes:
  01postgres18_var_lib_postgresql:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_01postgres18_var_lib_postgresql
