---
services:
  01redis:
    init: ${DOCKER_INIT}
    image: redis:${GLOBAL_STACK_REDIS_VERSION}
    ports:
      - ${GLOBAL_STACK_REDIS_PORT_6379:-}6379
    volumes:
      - 01redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      stack.service: "01redis"
      stack.tier: "cache"
      stack.version: "${GLOBAL_STACK_VERSION}"
    restart: "on-failure:5"
    networks:
      - public
volumes:
  01redis_data:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_01redis_data
