---
services:
  02phpbrew:
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/02phpbrew/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - 00base
    extra_hosts:
      - ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    environment:
      - PHPBREW_MODE=install
      - GLOBAL_STACK_COMPOSER_VERSION=${GLOBAL_STACK_COMPOSER_VERSION}
      - GLOBAL_STACK_DEPLOYER_VERSION=${GLOBAL_STACK_DEPLOYER_VERSION}
      - GLOBAL_STACK_FABPOT_LOCAL_PHP_SECURITY_CHECKER_VERSION=${GLOBAL_STACK_FABPOT_LOCAL_PHP_SECURITY_CHECKER_VERSION}
      - GLOBAL_STACK_FRANKENPHP_VERSION=${GLOBAL_STACK_FRANKENPHP_VERSION}
      - GLOBAL_STACK_PHALCON_DEVTOOLS_VERSION=${GLOBAL_STACK_PHALCON_DEVTOOLS_VERSION}
      - GLOBAL_STACK_PHPBREW_VERSION=${GLOBAL_STACK_PHPBREW_VERSION}
      - GLOBAL_STACK_PICKLE_VERSION=${GLOBAL_STACK_PICKLE_VERSION}
      - GLOBAL_STACK_RELOAD_PHPBREW=${GLOBAL_STACK_RELOAD_PHPBREW}
      - GLOBAL_STACK_SYMFONY_CLI_VERSION=${GLOBAL_STACK_SYMFONY_CLI_VERSION}
      - GLOBAL_STACK_ZEPHIR_LANG_VERSION=${GLOBAL_STACK_ZEPHIR_LANG_VERSION}
      - PHPBREW_BIN=${GLOBAL_STACK_PHPBREW_BIN}
      - PHPBREW_HOME=${GLOBAL_STACK_PHPBREW_HOME}
      - PHPBREW_ROOT=${GLOBAL_STACK_PHPBREW_ROOT}
      - PHPBREW_SRC=${GLOBAL_STACK_PHPBREW_SRC}
      - PHPBREW_SET_PROMPT=${GLOBAL_STACK_PHPBREW_SET_PROMPT}
      - PHPBREW_SKIP_INIT=${GLOBAL_STACK_PHPBREW_SKIP_INIT}
      - PHPBREW_RC_ENABLE=${GLOBAL_STACK_PHPBREW_RC_ENABLE}
      - COMPOSER_HOME=${GLOBAL_STACK_COMPOSER_HOME}
      - COMPOSER_SOURCE=${GLOBAL_STACK_COMPOSER_SOURCE}
      - SYMFONY_HOME=${GLOBAL_STACK_SYMFONY_HOME}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    image: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}/local_global_stack_02phpbrew:${GLOBAL_STACK_VERSION}
    networks:
      - public
    ports:
      - ${GLOBAL_STACK_PHPBREW_PORT_9001:-}9001
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - ./docker/config/dist/conf:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/conf:rw
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
