---
services:
  02sonarqube:
    init: ${DOCKER_INIT}
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
        GLOBAL_STACK_DOCKER_USER_ID: ${GLOBAL_STACK_DOCKER_USER_ID}
        GLOBAL_STACK_SONARQUBE_VERSION: ${GLOBAL_STACK_SONARQUBE_VERSION}
      context: ./
      dockerfile: ./docker/images/02sonarqube/Dockerfile
    depends_on:
      - 00base
      - 01postgres18
    extra_hosts:
      - ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    environment:
      - CAROOT=${GLOBAL_STACK_CAROOT}
      - GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES=${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}
      - SONAR_JDBC_URL=${GLOBAL_STACK_SONARQUBE_JDBC_URL}
      - SONAR_JDBC_USERNAME=${GLOBAL_STACK_SONARQUBE_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${GLOBAL_STACK_SONARQUBE_JDBC_PASSWORD}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - CURL_CA_BUNDLE=${GLOBAL_STACK_BASE_CURL_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - 02sonarqube_community_data:/opt/sonarqube/data
      - 02sonarqube_community_logs:/opt/sonarqube/logs
      - 02sonarqube_community_extensions:/opt/sonarqube/extensions
      - 02sonarqube_community_temp:/opt/sonarqube/temp
    ports:
      - ${GLOBAL_STACK_SONARQUBE_PORT_9000:-}9000
    networks:
      - public
    restart: unless-stopped
volumes:
  02sonarqube_community_data:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_02sonarqube_community_data
  02sonarqube_community_logs:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_02sonarqube_community_logs
  02sonarqube_community_extensions:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_02sonarqube_community_extensions
  02sonarqube_community_temp:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_02sonarqube_community_temp
