---
services:
  ghost-blog:
    init: ${DOCKER_INIT}
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
        GLOBAL_STACK_SHELL_HISTORY: ${GLOBAL_STACK_SHELL_HISTORY}
        GLOBAL_STACK_IMAGE_GHOST_BLOG_VERSION: ${GLOBAL_STACK_IMAGE_GHOST_BLOG_VERSION}
      context: ./
      dockerfile: ./docker/images/01ghost-blog/Dockerfile
    depends_on:
      00base:
        condition: service_healthy
        required: true
      01mariadb11:
        condition: service_healthy
        required: true
    environment:
      - database__client=mysql
      - database__connection__database=${GLOBAL_STACK_ITRNL_BLG_APP_GHOST_DATABASE}
      - database__connection__host=01mariadb11
      - database__connection__password=${GLOBAL_STACK_DATABASE_ROOT_PASSWORD}
      - database__connection__user=root
      - url=${GLOBAL_STACK_ITRNL_BLG_APP_GHOST_URL}
      - CAROOT=${GLOBAL_STACK_CAROOT}
      - GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES=${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}
      - GLOBAL_STACK_DOCKER_TOOLS_PATH_ERRORS=${GLOBAL_STACK_DOCKER_TOOLS_PATH_ERRORS}
      - GLOBAL_STACK_DOCKER_ROOT_DIST_PATH=${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
      - GLOBAL_STACK_DOCKER_USER_EMAIL=${GLOBAL_STACK_DOCKER_USER_EMAIL}
      - GLOBAL_STACK_DOCKER_USER_NAME=${GLOBAL_STACK_DOCKER_USER_NAME}
    extra_hosts:
      - ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2368/ 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 99999
      start_period: 24h
    labels:
      stack.service: "ghost-blog"
      stack.tier: "tool"
      stack.version: "${GLOBAL_STACK_VERSION}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      public: ~
    ports:
      - ${GLOBAL_STACK_ITRNL_BLG_APP_GHOST_PORT_2368:-}2368
    restart: unless-stopped
    volumes:
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - ./docker/config/dist/conf:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/conf:rw
      - ./${GLOBAL_STACK_ITRNL_BLG_APP_GHOST_CONTENT_HOST_PATH}:/var/lib/ghost/content
