---
services:
  04android:
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
        GLOBAL_STACK_ANDROID_LOCALE: ${GLOBAL_STACK_ANDROID_LOCALE}
        GLOBAL_STACK_ANDROID_SET_LOCALE: ${GLOBAL_STACK_ANDROID_SET_LOCALE}
      context: ./
      dockerfile: ./docker/images/04android/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - 00base
      - 02sdkman
      - 02rbenv
      - 02nvm
      - 03java24-zulu
      - 03ruby3
      - 03node24
    environment:
      - GLOBAL_STACK_SDKMAN_VERSION=${GLOBAL_STACK_SDKMAN_VERSION}
      - SDKMAN_DIR=${GLOBAL_STACK_SDKMAN_DIR}
      - JAVA_VERSION_AS=24
      - JAVA_VERSION=${GLOBAL_STACK_JAVA24_VERSION}
      - SDKMAN_CONFIG_PACKAGE_01_ANT_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_ANT_NAME}
      - SDKMAN_INSTALL_PACKAGE_01_ANT_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_ANT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_02_GRADLE_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_GRADLE_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_02_GRADLE_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_GRADLE_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_03_KOTLIN_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_KOTLIN_NAME}
      - SDKMAN_INSTALL_PACKAGE_03_KOTLIN_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_KOTLIN_VERSION}
      - SDKMAN_CONFIG_PACKAGE_04_MAVEN_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_MAVEN_VX1_NAME}
      - SDKMAN_INSTALL_PACKAGE_04_MAVEN_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_MAVEN_VX1_VERSION}
      - SDKMAN_CONFIG_PACKAGE_05_POMCHECKER_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_POMCHECKER_NAME}
      - SDKMAN_INSTALL_PACKAGE_05_POMCHECKER_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_POMCHECKER_VERSION}
      - SDKMAN_CONFIG_PACKAGE_06_SPRINGBOOT_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_SPRINGBOOT_NAME}
      - SDKMAN_INSTALL_PACKAGE_06_SPRINGBOOT_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_SPRINGBOOT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_07_TOMCAT_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_TOMCAT_NAME}
      - SDKMAN_INSTALL_PACKAGE_07_TOMCAT_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_TOMCAT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_08_GROOVY_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_GROOVY_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_08_GROOVY_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_GROOVY_VX2_VERSION}
      - SDKMAN_CONFIG_PACKAGE_09_MICRONAUT_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_MICRONAUT_NAME}
      - SDKMAN_INSTALL_PACKAGE_09_MICRONAUT_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_MICRONAUT_VERSION}
      - SDKMAN_CONFIG_PACKAGE_10_QUARKUS_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_QUARKUS_NAME}
      - SDKMAN_INSTALL_PACKAGE_10_QUARKUS_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_QUARKUS_VERSION}
      - SDKMAN_CONFIG_PACKAGE_11_SPARK_NAME=${GLOBAL_STACK_JAVA24_CONFIG_PACKAGE_SPARK_VX2_NAME}
      - SDKMAN_INSTALL_PACKAGE_11_SPARK_VERSION=${GLOBAL_STACK_JAVA24_INSTALL_PACKAGE_SPARK_VX2_VERSION}
      - GLOBAL_STACK_RBENV_VERSION=${GLOBAL_STACK_RBENV_VERSION}
      - GLOBAL_STACK_RBENV_RUBY_BUILD_VERSION=${GLOBAL_STACK_RBENV_RUBY_BUILD_VERSION}
      - GLOBAL_STACK_RBENV_GEMSET_VERSION=${GLOBAL_STACK_RBENV_GEMSET_VERSION}
      - GLOBAL_STACK_RELOAD_RUBY=${GLOBAL_STACK_RELOAD_RUBY}
      - RBENV_ROOT=${GLOBAL_STACK_RBENV_ROOT}
      - RUBY_CONFIG_PACKAGE_01_GOOGLE_API_CLIENT_NAME=${GLOBAL_STACK_RUBY3_CONFIG_PACAKGE_GOOGLE_API_CLIENT_NAME}
      - RUBY_INSTALL_PACKAGE_01_GOOGLE_API_CLIENT_VERSION=${GLOBAL_STACK_RUBY3_INSTALL_PACAKGE_GOOGLE_API_CLIENT_VERSION}
      - RUBY_CONFIG_PACKAGE_02_FASTLANE_NAME=${GLOBAL_STACK_RUBY3_CONFIG_PACAKGE_FASTLANE_NAME}
      - RUBY_INSTALL_PACKAGE_02_FASTLANE_VERSION=${GLOBAL_STACK_RUBY3_INSTALL_PACAKGE_FASTLANE_VERSION}
      - RUBY_VERSION=${GLOBAL_STACK_RUBY3_VERSION}
      - RUBY_VERSION_AS=3
      - GLOBAL_STACK_DENO_ALEPH_VERSION=${GLOBAL_STACK_DENO_ALEPH_VERSION}
      - GLOBAL_STACK_DENO_MANDARINETS_VERSION=${GLOBAL_STACK_DENO_MANDARINETS_VERSION}
      - GLOBAL_STACK_DENO_VERSION=${GLOBAL_STACK_DENO_VERSION}
      - GLOBAL_STACK_NVM_VERSION=${GLOBAL_STACK_NVM_VERSION}
      - GLOBAL_STACK_RELOAD_NVM=${GLOBAL_STACK_RELOAD_NVM}
      - DENO_INSTALL=${GLOBAL_STACK_DENO_INSTALL}
      - DENO_INSTALL_ROOT=${GLOBAL_STACK_DENO_INSTALL_ROOT}
      - DENO_DIR=${GLOBAL_STACK_DENO_DIR}
      - NVM_DIR=${GLOBAL_STACK_NVM_DIR}
      - YARN_OFFLINE_MIRROR=${GLOBAL_STACK_YARN_OFFLINE_MIRROR}
      - YARN_CACHE_FOLDER=${GLOBAL_STACK_YARN_CACHE_FOLDER}
      - YARN_GLOBAL_FOLDER=${GLOBAL_STACK_YARN_GLOBAL_FOLDER}
      - GLOBAL_STACK_PNPM_GLOBAL_DIR=${GLOBAL_STACK_PNPM_GLOBAL_DIR}
      - PNPM_HOME=${GLOBAL_STACK_PNPM_GLOBAL_DIR}
      - GLOBAL_STACK_PNPM_STORE_DIR=${GLOBAL_STACK_PNPM_STORE_DIR}
      - NPM_CACHE_DIR=${GLOBAL_STACK_NPM_CACHE_DIR}
      - CYPRESS_CACHE_FOLDER=${GLOBAL_STACK_CYPRESS_CACHE_FOLDER}
      - NODE_VERSION_AS=22
      - NODE_VERSION=${GLOBAL_STACK_NODE22_VERSION}
      - GLOBAL_STACK_NODE_UPGRADE=${GLOBAL_STACK_NODE22_UPGRADE}
      - GLOBAL_STACK_NODE_UPGRADE_ALL=${GLOBAL_STACK_NODE22_UPGRADE_ALL}
      - GLOBAL_STACK_ANDROID_BUILD_TOOLS_VERSION=${GLOBAL_STACK_ANDROID_BUILD_TOOLS_VERSION}
      - GLOBAL_STACK_ANDROID_FLUTTER_VERSION=${GLOBAL_STACK_ANDROID_FLUTTER_VERSION}
      - GLOBAL_STACK_ANDROID_INSTALL_SYSTEM_IMAGES=${GLOBAL_STACK_ANDROID_INSTALL_SYSTEM_IMAGES}
      - GLOBAL_STACK_ANDROID_NDK_VERSION=${GLOBAL_STACK_ANDROID_NDK_VERSION}
      - GLOBAL_STACK_ANDROID_NDK_BUNDLE_VERSION=${GLOBAL_STACK_ANDROID_NDK_BUNDLE_VERSION}
      - GLOBAL_STACK_ANDROID_PLATFORM_TOOLS_VERSION=${GLOBAL_STACK_ANDROID_PLATFORM_TOOLS_VERSION}
      - GLOBAL_STACK_ANDROID_SDK_URL=${GLOBAL_STACK_ANDROID_SDK_URL}
      - GLOBAL_STACK_RELOAD_ANDROID=${GLOBAL_STACK_RELOAD_ANDROID}
      - ANDROID_HOME=${GLOBAL_STACK_ANDROID_HOME}
      - ANDROID_SDK_ROOT=${GLOBAL_STACK_ANDROID_SDK_ROOT}
      - ANDROID_SDK_HOME=${GLOBAL_STACK_ANDROID_SDK_HOME}
      - ANDROID_NDK_HOME=${GLOBAL_STACK_ANDROID_NDK_HOME}
      - GRADLE_USER_HOME=${GLOBAL_STACK_GRADLE_USER_HOME}
      - PUB_CACHE=${GLOBAL_STACK_PUB_CACHE}
      - FLUTTER_HOME=${GLOBAL_STACK_FLUTTER_HOME}
      - ANDROID_ADB_SERVER_ADDRESS=${GLOBAL_STACK_DOCKER_HOST_DSN}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    extra_hosts:
      - ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    image: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}/local_global_stack_04android:${GLOBAL_STACK_VERSION}
    networks:
      - public
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - ./docker/config/dist/conf:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/conf:rw
      - /dev/bus/usb:/dev/bus/usb
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
