---
services:
  03php8-2:
    extends:
      file: docker/config/compose-fragments/php-packages.compose.yaml
      service: php-packages
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/03php8-2/Dockerfile
    depends_on:
      00base:
        condition: service_healthy
        required: true
      02phpbrew:
        condition: service_healthy
        required: true
    environment:
      - PHPBREW_MODE=setup
      - GLOBAL_STACK_COMPOSER_VERSION=${GLOBAL_STACK_COMPOSER_VERSION}
      - GLOBAL_STACK_DEPLOYER_VERSION=${GLOBAL_STACK_DEPLOYER_VERSION}
      - GLOBAL_STACK_FABPOT_LOCAL_PHP_SECURITY_CHECKER_VERSION=${GLOBAL_STACK_FABPOT_LOCAL_PHP_SECURITY_CHECKER_VERSION}
      - GLOBAL_STACK_FRANKENPHP_VERSION=${GLOBAL_STACK_FRANKENPHP_8_2_VERSION}
      - GLOBAL_STACK_PHALCON_DEVTOOLS_VERSION=${GLOBAL_STACK_PHALCON_DEVTOOLS_VERSION}
      - GLOBAL_STACK_PHPBREW_VERSION=${GLOBAL_STACK_PHPBREW_VERSION}
      - GLOBAL_STACK_PICKLE_VERSION=${GLOBAL_STACK_PICKLE_VERSION}
      - GLOBAL_STACK_PIE_VERSION=${GLOBAL_STACK_PIE_VERSION}
      - GLOBAL_STACK_MAGO_VERSION=${GLOBAL_STACK_MAGO_VERSION}
      - GLOBAL_STACK_CASTOR_VERSION=${GLOBAL_STACK_CASTOR_VERSION}
      - GLOBAL_STACK_RELOAD_PHPBREW=${GLOBAL_STACK_RELOAD_PHPBREW}
      - GLOBAL_STACK_RELOAD_PHP=${GLOBAL_STACK_RELOAD_PHP8_2}
      - GLOBAL_STACK_SYMFONY_CLI_VERSION=${GLOBAL_STACK_SYMFONY_CLI_VERSION}
      - GLOBAL_STACK_ZEPHIR_LANG_VERSION=${GLOBAL_STACK_ZEPHIR_LANG_VERSION}
      - PHPBREW_BIN=${GLOBAL_STACK_PHPBREW_BIN}
      - PHPBREW_HOME=${GLOBAL_STACK_PHPBREW_HOME}
      - PHPBREW_ROOT=${GLOBAL_STACK_PHPBREW_ROOT}
      - PHPBREW_SRC=${GLOBAL_STACK_PHPBREW_SRC}
      - PHPBREW_SET_PROMPT=${GLOBAL_STACK_PHPBREW_SET_PROMPT}
      - PHPBREW_SKIP_INIT=${GLOBAL_STACK_PHPBREW_SKIP_INIT}
      - PHPBREW_RC_ENABLE=${GLOBAL_STACK_PHPBREW_RC_ENABLE}
      - COMPOSER_HOME=${GLOBAL_STACK_COMPOSER_HOME}
      - COMPOSER_SOURCE=${GLOBAL_STACK_COMPOSER_SOURCE}
      - SYMFONY_HOME=${GLOBAL_STACK_SYMFONY_HOME}
      - PHP_VERSION=${GLOBAL_STACK_PHP8_2_VERSION}
      - PHP_VERSION_NAME=${GLOBAL_STACK_PHP8_2_VERSION_NAME}
      - PHP_VERSION_AS=${GLOBAL_STACK_PHP8_2_VERSION_AS}
      - PHP_INSTALL_CLI_VARIANTS=${GLOBAL_STACK_PHP8_2_CLI_VARIANTS}
      - PHP_INSTALL_CLI_OPTIONS=${GLOBAL_STACK_PHP8_2_CLI_OPTIONS}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - CURL_CA_BUNDLE=${GLOBAL_STACK_BASE_CURL_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
      - GLOBAL_STACK_DOCKER_USER_EMAIL=${GLOBAL_STACK_DOCKER_USER_EMAIL}
      - GLOBAL_STACK_DOCKER_USER_NAME=${GLOBAL_STACK_DOCKER_USER_NAME}
      - GLOBAL_STACK_ERROR_TOKEN=php.${GLOBAL_STACK_PHP8_2_VERSION_AS}
    image: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}/local_global_stack_03php8-2:${GLOBAL_STACK_VERSION}
    ports:
      - ${GLOBAL_STACK_PHP8_2_PORT_9001:-}9001
      - ${GLOBAL_STACK_PHP8_2_FRANKENPHP_PORT_8080:-}8080
      - ${GLOBAL_STACK_PHP8_2_FRANKENPHP_PORT_8443:-}8443
      - ${GLOBAL_STACK_PHP8_2_FRANKENPHP_PORT_2019:-}2019
    healthcheck:
      test: ["CMD-SHELL", "! test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_ERRORS}/php.${GLOBAL_STACK_PHP8_2_VERSION_AS} && test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}/php.${GLOBAL_STACK_PHP8_2_VERSION_AS} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 99999
      start_period: 24h
    labels:
      stack.service: "03php8-2"
      stack.tier: "runtime"
      stack.version: "${GLOBAL_STACK_VERSION}"
