---
services:
  03ruby3:
    extends:
      file: docker/config/compose-fragments/base-6vol.compose.yaml
      service: base-6vol
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}
        GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
      context: ./
      dockerfile: ./docker/images/03ruby3/Dockerfile
    depends_on:
      00base:
        condition: service_healthy
        required: true
      02rbenv:
        condition: service_healthy
        required: true
    environment:
      - RBENV_MODE=setup
      - GLOBAL_STACK_RBENV_VERSION=${GLOBAL_STACK_RBENV_VERSION}
      - GLOBAL_STACK_RBENV_RUBY_BUILD_VERSION=${GLOBAL_STACK_RBENV_RUBY_BUILD_VERSION}
      - GLOBAL_STACK_RBENV_GEMSET_VERSION=${GLOBAL_STACK_RBENV_GEMSET_VERSION}
      - GLOBAL_STACK_RELOAD_RUBY=${GLOBAL_STACK_RELOAD_RUBY}
      - RBENV_ROOT=${GLOBAL_STACK_RBENV_ROOT}
      - RUBY_CONFIG_PACKAGE_DUMMY_NAME=dummy
      - RUBY_INSTALL_PACKAGE_DUMMY_VERSION=0
      - RUBY_CONFIG_PACKAGE_01_GOOGLE_API_CLIENT_NAME=${GLOBAL_STACK_RUBY_CONFIG_PACKAGE_GOOGLE_API_CLIENT_NAME}
      - RUBY_INSTALL_PACKAGE_01_GOOGLE_API_CLIENT_VERSION=${GLOBAL_STACK_RUBY_INSTALL_PACKAGE_GOOGLE_API_CLIENT_VERSION}
      - RUBY_CONFIG_PACKAGE_02_FASTLANE_NAME=${GLOBAL_STACK_RUBY_CONFIG_PACKAGE_FASTLANE_NAME}
      - RUBY_INSTALL_PACKAGE_02_FASTLANE_VERSION=${GLOBAL_STACK_RUBY_INSTALL_PACKAGE_FASTLANE_VERSION}
      - RUBY_VERSION=${GLOBAL_STACK_RUBY3_VERSION}
      - RUBY_VERSION_AS=${GLOBAL_STACK_RUBY3_VERSION_AS}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - CURL_CA_BUNDLE=${GLOBAL_STACK_BASE_CURL_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
      - GLOBAL_STACK_DOCKER_USER_EMAIL=${GLOBAL_STACK_DOCKER_USER_EMAIL}
      - GLOBAL_STACK_DOCKER_USER_NAME=${GLOBAL_STACK_DOCKER_USER_NAME}
      - GLOBAL_STACK_ERROR_TOKEN=ruby.${GLOBAL_STACK_RUBY3_VERSION_AS}
    image: ${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_DOCKER_LOCAL_REGISTRY_PORT_5000}/local_global_stack_03ruby3:${GLOBAL_STACK_VERSION}
    healthcheck:
      test: ["CMD-SHELL", "! test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_ERRORS}/ruby.${GLOBAL_STACK_RUBY3_VERSION_AS} && test -f ${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}/ruby.${GLOBAL_STACK_RUBY3_VERSION_AS} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 99999
      start_period: 24h
    labels:
      stack.service: "03ruby3"
      stack.tier: "runtime"
      stack.version: "${GLOBAL_STACK_VERSION}"
