---
services:
  01mariadb12:
    init: true
    build:
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_SHELL_HISTORY: ${GLOBAL_STACK_SHELL_HISTORY}
        GLOBAL_STACK_IMAGE_MARIADB12_VERSION: ${GLOBAL_STACK_IMAGE_MARIADB12_VERSION}
        GLOBAL_STACK_IMAGE_UBUNTU_NOBLE_VERSION: ${GLOBAL_STACK_IMAGE_UBUNTU_NOBLE_VERSION}
      context: ./
      dockerfile: ./docker/images/01mariadb12/Dockerfile
    command:
      - mariadbd
      - --default-authentication-plugin=caching_sha2_password
      - --character-set-server=${GLOBAL_STACK_DATABASE_CHARSET}
      - --collation-server=${GLOBAL_STACK_DATABASE_COLLATE}
    depends_on:
      - 00base
    environment:
      - MARIADB_DBS=${GLOBAL_STACK_MARIADB12_DBS}
      - MYSQL_PASSWORD=${GLOBAL_STACK_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${GLOBAL_STACK_DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${GLOBAL_STACK_DATABASE_USER}
      - GLOBAL_STACK_DATABASE_CHARSET=${GLOBAL_STACK_DATABASE_CHARSET}
      - GLOBAL_STACK_DATABASE_COLLATE=${GLOBAL_STACK_DATABASE_COLLATE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=${GLOBAL_STACK_TIMEZONE}
    networks:
      - public
    ports:
      - ${GLOBAL_STACK_MARIADB12_PORT_3306:-}3306
    volumes:
      - ./docker/data/dumps/mariadb/12:/opt/dumps:rw
      - 01mariadb12_data:/var/lib/mysql:rw,delegated
        # - ./var/database-history/.mariadb_history:/root/.mariadb_history:rw,delegated
        # - source: ./docker/logs/mariadb/12
        #   target: /var/log/mysql
        #   type: bind
volumes:
  01mariadb12_data:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_01mariadb12_data
