---
services:
  00base:
    init: ${DOCKER_INIT}
    build:
      context: ./
      dockerfile: ./docker/images/00base/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        GLOBAL_STACK_SHELL_RC_TARGET: ${GLOBAL_STACK_SHELL_RC_TARGET}
        GLOBAL_STACK_SHELL: ${GLOBAL_STACK_SHELL}
        GLOBAL_STACK_INSTALL_ANSIBLE: ${GLOBAL_STACK_INSTALL_ANSIBLE}
        GLOBAL_STACK_GO_VERSION: ${GLOBAL_STACK_GO_VERSION}
        GOROOT: ${GLOBAL_STACK_GOROOT}
        GOPATH: ${GLOBAL_STACK_GOPATH}
        GLOBAL_STACK_ZIG_VERSION: ${GLOBAL_STACK_ZIG_VERSION}
        ZIGPATH: ${GLOBAL_STACK_ZIGPATH}
        HURLPATH: ${GLOBAL_STACK_HURLPATH}
        GLOBAL_STACK_CARGO_HOME: ${GLOBAL_STACK_CARGO_HOME}
        GLOBAL_STACK_BASE_INSTALL_TOOLS: ${GLOBAL_STACK_BASE_INSTALL_TOOLS}
        GLOBAL_STACK_SONAR_SCANNER_CLI_VERSION: ${GLOBAL_STACK_SONAR_SCANNER_CLI_VERSION}
        GLOBAL_STACK_DOCKER_BUILDX_VERSION: ${GLOBAL_STACK_DOCKER_BUILDX_VERSION}
        GLOBAL_STACK_DOCKER_COMPOSE_V1_VERSION: ${GLOBAL_STACK_DOCKER_COMPOSE_V1_VERSION}
        GLOBAL_STACK_DOCKER_COMPOSE_V2_VERSION: ${GLOBAL_STACK_DOCKER_COMPOSE_V2_VERSION}
        GLOBAL_STACK_DOCKER_GROUP_ID: ${GLOBAL_STACK_DOCKER_GROUP_ID}
        GLOBAL_STACK_DOCKER_GROUP_UID: ${GLOBAL_STACK_DOCKER_GROUP_UID}
        GLOBAL_STACK_DOCKER_IN_DOCKER: ${GLOBAL_STACK_DOCKER_IN_DOCKER}
        GLOBAL_STACK_DOCKER_IN_DOCKER_ACTIVATE_BUILDX: ${GLOBAL_STACK_DOCKER_IN_DOCKER_ACTIVATE_BUILDX}
        GLOBAL_STACK_DOCKER_ROOT_PATH: ${GLOBAL_STACK_DOCKER_ROOT_PATH}
        GLOBAL_STACK_DOCKER_TOOLS_PATH: ${GLOBAL_STACK_DOCKER_TOOLS_PATH}
        GLOBAL_STACK_DOCKER_USER_ID: ${GLOBAL_STACK_DOCKER_USER_ID}
        GLOBAL_STACK_DOCKER_PASSWORD: ${GLOBAL_STACK_DOCKER_PASSWORD}
        GLOBAL_STACK_DOCKER_USER_UID: ${GLOBAL_STACK_DOCKER_USER_UID}
        GLOBAL_STACK_DOCKER_WORKDIR: ${GLOBAL_STACK_DOCKER_WORKDIR}
        GLOBAL_STACK_INSTALL_GITLAB_RUNNER: ${GLOBAL_STACK_INSTALL_GITLAB_RUNNER}
        GLOBAL_STACK_HADOLINT_VERSION: ${GLOBAL_STACK_HADOLINT_VERSION}
        GLOBAL_STACK_IMAGE_UBUNTU_NOBLE_VERSION: ${GLOBAL_STACK_IMAGE_UBUNTU_NOBLE_VERSION}
        GLOBAL_STACK_MKCERT_VERSION: ${GLOBAL_STACK_MKCERT_VERSION}
        GLOBAL_STACK_INSTALL_PODMAN: ${GLOBAL_STACK_INSTALL_PODMAN}
        GLOBAL_STACK_PODMAN_COMPOSE_VERSION: ${GLOBAL_STACK_PODMAN_COMPOSE_VERSION}
        GLOBAL_STACK_PODMAN_CHANEL: ${GLOBAL_STACK_PODMAN_CHANEL}
        GLOBAL_STACK_RELOAD_ALL: ${GLOBAL_STACK_RELOAD_ALL}
        GLOBAL_STACK_SHELL_CHECK_VERSION: ${GLOBAL_STACK_SHELL_CHECK_VERSION}
        GLOBAL_STACK_GITLEAKS_VERSION: ${GLOBAL_STACK_GITLEAKS_VERSION}
        GLOBAL_STACK_DIFFTASTIC_VERSION: ${GLOBAL_STACK_DIFFTASTIC_VERSION}
        GLOBAL_STACK_SHFMT_VERSION: ${GLOBAL_STACK_SHFMT_VERSION}
        GLOBAL_STACK_MISE_VERSION: ${GLOBAL_STACK_MISE_VERSION}
        GLOBAL_STACK_BAT_VERSION: ${GLOBAL_STACK_BAT_VERSION}
        GLOBAL_STACK_TASK_VERSION: ${GLOBAL_STACK_TASK_VERSION}
        GLOBAL_STACK_SOPS_VERSION: ${GLOBAL_STACK_SOPS_VERSION}
        GLOBAL_STACK_YQ_VERSION: ${GLOBAL_STACK_YQ_VERSION}
        GLOBAL_STACK_YAMLFMT_VERSION: ${GLOBAL_STACK_YAMLFMT_VERSION}
        GLOBAL_STACK_HURL_VERSION: ${GLOBAL_STACK_HURL_VERSION}
        GLOBAL_STACK_JUJUTSU_VERSION: ${GLOBAL_STACK_JUJUTSU_VERSION}
        GLOBAL_STACK_MERGIRAF_VERSION: ${GLOBAL_STACK_MERGIRAF_VERSION}
        GLOBAL_STACK_TIMEZONE: ${GLOBAL_STACK_TIMEZONE}
        GLOBAL_STACK_UNU: ${GLOBAL_STACK_UNU}
        GLOBAL_STACK_USE_LOCKS: ${GLOBAL_STACK_USE_LOCKS}
        GLOBAL_STACK_VERSION: ${GLOBAL_STACK_VERSION}
        MISE_VERSION: ${GLOBAL_STACK_MISE_VERSION}
        MISE_DEBUG: ${GLOBAL_STACK_MISE_DEBUG}
        MISE_QUIET: ${GLOBAL_STACK_MISE_QUIET}
        MISE_INSTALL_PATH: ${GLOBAL_STACK_MISE_INSTALL_PATH}
        MISE_DATA_DIR: ${GLOBAL_STACK_MISE_DATA_DIR}
        MISE_STATE_DIR: ${GLOBAL_STACK_MISE_STATE_DIR}
        MISE_CONFIG_DIR: ${GLOBAL_STACK_MISE_CONFIG_DIR}
        MISE_CACHE_DIR: ${GLOBAL_STACK_MISE_CACHE_DIR}
        CAROOT: ${GLOBAL_STACK_CAROOT}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_BIN: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_BIN}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_VERSIONS: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_VERSIONS}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_SUCCESSES}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_LOCKS: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_LOCKS}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_SHELLRC: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_SHELLRC}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_CACHE: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_CACHE}
        GLOBAL_STACK_DOCKER_ROOT_DIST_PATH: ${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}
        GLOBAL_STACK_DOCKER_TOOLS_PATH_LOGS: ${GLOBAL_STACK_DOCKER_TOOLS_PATH_LOGS}
        GLOBAL_STACK_SSL_PATH: ${GLOBAL_STACK_SSL_PATH}
        GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_AWSCLI_LOCAL_VERSION: ${GLOBAL_STACK_PYTHON3_INSTALL_PACKAGE_AWSCLI_LOCAL_VERSION}
        GLOBAL_STACK_WKHTMLTOPDF_VERSION: ${GLOBAL_STACK_WKHTMLTOPDF_VERSION}
        GLOBAL_STACK_WKHTMLTOPDF_DISTRO: ${GLOBAL_STACK_WKHTMLTOPDF_DISTRO}
        GLOBAL_STACK_AUTOMAKE_VERSION: ${GLOBAL_STACK_AUTOMAKE_VERSION}
        GLOBAL_STACK_AUTOMAKE_MIRROR: ${GLOBAL_STACK_AUTOMAKE_MIRROR}
    image: ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_LOCAL_REGISTRY_PORT_5000}/local_global_stack_00base:${GLOBAL_STACK_VERSION}
    networks:
      - public
    cap_add:
      - NET_ADMIN
    environment:
      - GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS=${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}
      - GLOBAL_STACK_HTTPS_LOCALHOST_IPS=${GLOBAL_STACK_HTTPS_LOCALHOST_IPS}
      - GLOBAL_STACK_HTTPS_CONTAINER_IPS=${GLOBAL_STACK_HTTPS_CONTAINER_IPS}
      - AWS_ENDPOINT_URL_S3=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_S3}
      - AWS_ENDPOINT_URL_SQS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SQS}
      - AWS_ENDPOINT_URL_LAMBDA=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_LAMBDA}
      - AWS_ENDPOINT_URL_SNS=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS}
      - AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT=${GLOBAL_STACK_BASE_AWS_ENDPOINT_URL_SNS_NOTIFICATION_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${GLOBAL_STACK_BASE_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${GLOBAL_STACK_BASE_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${GLOBAL_STACK_BASE_AWS_REGION}
      - AWS_DEFAULT_REGION=${GLOBAL_STACK_BASE_AWS_DEFAULT_REGION}
      - AWS_CA_BUNDLE=${GLOBAL_STACK_BASE_AWS_CA_BUNDLE}
      - NODE_EXTRA_CA_CERTS=${GLOBAL_STACK_BASE_NODE_EXTRA_CA_CERTS}
      - SSL_CERT_FILE=${GLOBAL_STACK_BASE_SSL_CERT_FILE}
      - REQUESTS_CA_BUNDLE=${GLOBAL_STACK_BASE_REQUESTS_CA_BUNDLE}
      - CURL_CA_BUNDLE=${GLOBAL_STACK_BASE_CURL_CA_BUNDLE}
      - SERVERLESS_ACCESS_KEY=${GLOBAL_STACK_BASE_SERVERLESS_ACCESS_KEY}
    extra_hosts:
      - ${GLOBAL_STACK_LOCAL_REGISTRY_ALIAS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_DOCKER_HOST_DSN}:${GLOBAL_STACK_HOST_GATEWAY_IP}
      - ${GLOBAL_STACK_EXPOSED_VIRTUAL_HOSTS}:${GLOBAL_STACK_HOST_GATEWAY_IP}
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:rw,delegated
      - ./projects:${GLOBAL_STACK_DOCKER_WORKDIR}:rw
      - ./tools:${GLOBAL_STACK_DOCKER_TOOLS_PATH}:rw
      - ./${GLOBAL_STACK_SHELL_HISTORY}:/home/${GLOBAL_STACK_DOCKER_USER_ID}/${GLOBAL_STACK_SHELL_HISTORY_TARGET}:rw
      - ./docker/config/root:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/home/user:rw
      - ./docker/config/dist/bin:${GLOBAL_STACK_DOCKER_ROOT_DIST_PATH}/bin:rw
      - 00base_lib_docker:/var/lib/docker:rw,delegated
    privileged: true
    restart: unless-stopped
    working_dir: ${GLOBAL_STACK_DOCKER_WORKDIR}
volumes:
  00base_lib_docker:
    name: ${COMPOSE_PROJECT_NAME}_${GLOBAL_STACK_VERSION}_00base_lib_docker
